### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by milkpirate** [CyberDem0n/pam-oauth2#10]
Hey, could you add some examples, how to use it? E.g. for Github/Gitlab, Google, Microsoft aso.

**Comment by CyberDem0n** [comment]
I don't have anything more to add to what is already written in the README: https://github.com/CyberDem0n/pam-oauth2#how-it-works

The idea is very simple, you configure PAM, get the token from your IAM system and use this token instead of password.
Regarding Github/Gitlab, Google, Microsoft and so on - I can't tell whether it will work without changes.

You may also check one of the existing forks, they are doing more advanced stuff and probably have more examples.
